altered email but may be broken now, damn

diff --git a/email b/email
--- a/email
+++ b/email
@@ -10,6 +10,8 @@ SMTP_PORT="587"
 SMTP_USERNAME="$EMAIL"
 SMTP_PASSWORD=$(pass $EMAIL_PASSWORD)
 
+HTML_FILE="$(parse $@ | jq -r '.args.parsed.html')" # plaintext is the default
+
 # email content
 TO="$(parse $@ | jq -r '.args.parsed.to')"
 SUBJECT="$(parse $@ | jq -r '.args.parsed.sub')"
@@ -22,7 +24,7 @@ prompt_user() {
   BODY=$(txtin -m -p 'COMPOSE MESSAGE, TERMINATE WITH EOF:\n')
 }
 
-send_email() {
+send_as_plaintext() {
   [[ "$TO" =~ ^(null|true)$ ]] && >&2 echo 'ERROR: NO RECIPIENT (-to)' && exit 1
   [[ "$BODY" =~ ^(null|true)$ ]] && >&2 echo 'ERROR: EMPTY MESSAGE (-msg)' && exit 2
   [[ "$SUBJECT" =~ ^(''|null|true)$ ]] && >&2 echo 'WARNING: NO SUBJECT' && sleep 1 && SUBJECT=$(date)
@@ -43,6 +45,32 @@ send_email() {
   echo "Email sent to $TO"
 }
 
-[[ $# -eq 0 ]] && prompt_user
+send_as_multipart() {
+  [[ "$TO" =~ ^(null|true)$ ]] && >&2 echo 'ERROR: NO RECIPIENT (-to)' && exit 1
+  [[ "$BODY" =~ ^(null|true)$ ]] && >&2 echo 'ERROR: EMPTY MESSAGE (-msg)' && exit 2
+  [[ "$SUBJECT" =~ ^(''|null|true)$ ]] && >&2 echo 'WARNING: NO SUBJECT' && sleep 1 && SUBJECT=$(date)
+  
+  # Construct the email message
+  MESSAGE="Subject: $SUBJECT\n\n$BODY\n\n\n\n\n\n$FOOTNOTE"
+  
+  # Send the email using Curl
+  curl --show-error \
+       --url "smtp://$SMTP_SERVER:$SMTP_PORT" \
+       --ssl-reqd \
+       --mail-from "$SMTP_USERNAME" \
+       --mail-rcpt "$TO" \
+       --user "$SMTP_USERNAME:$SMTP_PASSWORD" \
+       --tlsv1.2 \
+       --upload-file "$BODY"
 
-send_email
+  echo "Email sent to $TO"
+}
+
+[[ $# -eq 0 ]] && prompt_user || parse $@ | jq -c '.'
+
+if [[ -n "$HTML_MODE" ]]; then
+  echo "SPECIAL MODE: HTML"
+  send_as_multipart
+else
+  send_as_plaintext
+fi
